#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Make sure that HAproxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend beni-frontend
        bind *:80
        mode http
        default_backend beni-backend
backend beni-backend
        balance roundrobin
        server 6544-web-01 52.91.34.203:80 check
        server 6544-web-02 54.152.215.14:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
